# Create a program that will play the 'cows and bulls' game with the user. The game works
# like this:
#
# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every
# digit that the user guessed correctly in the correct place, they have a 'cow'. For
# every digit the user guessed correctly in the wrong place is a 'bull.' Every time the
# user makes a guess, tell them how many 'cows' and 'bulls' they have. Once the user
# guesses the correct number, the game is over. Keep track of the number of guesses the
# user makes throughout the game and tell the user at the end.
#
# Say the number generated by the computer is 1038. An example interaction could look like
# this:
#
#   Welcome to the Cows and Bulls Game!
#   Enter a number:
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull

# Until the user guesses the number.


import random
number = str(random.randint(1000,9999)) #random 4 digit number
newlist = []

counter = 0
bulls = 0
item = 0
while True:
    user_input = raw_input("Enter a four digit number here: ")
    if user_input != number:
        for item in number:
            if item in number:
                if number[0] == user_input[0]:
                        counter = counter + 1
                if number[1] == user_input[1]:
                        counter = counter + 1
                if number[2] == user_input[2]:
                        counter = counter + 1
                if number[3] == user_input[3]:
                        counter = counter + 1
                if number[0] != user_input[0]:
                        bulls = bulls + 1
                if number[1] != user_input[1]:
                        bulls = bulls + 1
                if number[2] != user_input[2]:
                        bulls = bulls + 1
                if number[3] != user_input[3]:
                        bulls = bulls + 1
            if counter < 4 and bulls <= 4:
                print "You have", counter, "cow(s)"
            if counter < 4 and bulls <= 4:
                print "You have", bulls, "bull(s)"
            else:
                print
                print "Try again"
                break
    else:
        print "Congratulations, you guessed the number!"
        break






